FROM node:18-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:18-alpine AS runner
WORKDIR /app

ENV NODE_ENV production

COPY --from=builder /app/public ./public  # Ensure public directory exists
COPY --from=builder /app/.next ./.next    # Copy everything from .next

EXPOSE 3000

CMD ["node", ".next/standalone/server.js"]
