# Use the default Nginx configuration for Angular
# You can customize this further if needed
events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;

        # Redirect all requests to the root index.html file
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Include the default Nginx configuration for Angular
        # include /etc/nginx/conf.d/*.conf;
    }
}
