version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: homevideos_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bondstone
      POSTGRES_DB: homevideos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: homevideos_backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/homevideos_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: bondstone
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  frontend:
    build: ./frontend
    container_name: homevideos_frontend
    depends_on:
      - backend
    ports:
      - "8081:80"

  redis:
    image: redis:latest
    container_name: homevideos_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
