version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: homevideos_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bondstone
      POSTGRES_DB: homevideos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - homevideos_network

  backend:
    build: ./backend
    links:
      - redis
    container_name: homevideos_backend
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/homevideos_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: bondstone
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - homevideos_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: homevideos_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "https://homevideos.smbirch.com/api"
#      INTERNAL_API_URL: "http://backend:8080/api"
    networks:
      - homevideos_network

  redis:
    hostname: redis
    image: redis:latest
    container_name: homevideos_redis
    command: redis-server --bind 0.0.0.0
    ports:
      - "6379:6379"
    networks:
      - homevideos_network


networks:
  homevideos_network:

volumes:
  postgres_data: