version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: homevideos_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bondstone
      POSTGRES_DB: homevideos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: hpmevideos_backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: bondstone

  frontend:
    build: ./frontend
    container_name: homevideos_frontend
    depends_on:
      - backend
    ports:
      - "80:8002"